---
- hosts: localhost
  connection: local
  vars:
    avi_credentials:
      username: admin
      password: "{{ hostvars['jumpbox.student.lab']['Lab_avi_admin_password'] }}"
      controller: "{{ avi_controller }}"
    applications:
      - tenant: admin
        cloud_name: AWS
        desired_state: present
        name: test_one 
        hm_type: ping
        np_type: tcp
        ap_type: l4
        servers:
          "172.20.1.21": "80"
          "172.20.1.22": "80"
      - tenant: admin
        cloud_name: AWS
        desired_state: present
        name: another_test 
        hm_type: tcp
        np_type: tcp
        ap_type: l4
        servers:
          "172.20.1.21": "80"
          "172.20.1.22": "80"

  roles:
    - role: avinetworks.avisdk

  tasks:
    - include: avi_builder.yml
      with_items: "{{ applications }}"
      loop_control:
        loop_var: application

